version: "3.9"

services:
  verdaccio:
    image: verdaccio/verdaccio
    ports:
      - 4873:4873
    volumes:
      - ./config.yaml:/opt/verdaccio/conf/config.yaml
      - storage:/opt/verdaccio/storage

volumes:
  storage: